'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
exports.EntityRemoved = exports.Entity = exports.WatchableObjectSet = exports.ObjectSet = exports.World = exports.Trait = void 0;
const entity_1 = require("./entity");
exports.Entity = entity_1.default;
const trait_1 = require("./trait");
exports.Trait = trait_1.default;
const world_1 = require("./world");
exports.World = world_1.default;
const object_set_1 = require("./collections/object-set");
exports.ObjectSet = object_set_1.default;
const watchable_object_set_1 = require("./collections/watchable-object-set");
exports.WatchableObjectSet = watchable_object_set_1.default;
const entity_removed_1 = require("./events/entity-removed");
exports.EntityRemoved = entity_removed_1.default;
