"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.vector3 = exports.EntityRemoved = exports.Entity = exports.WatchableObjectSet = exports.ObjectSet = exports.EntityEventProcessed = exports.World = exports.Trait = void 0;
const entity_1 = require("./entity");
exports.Entity = entity_1.default;
const trait_1 = require("./trait");
exports.Trait = trait_1.default;
const world_1 = require("./world");
exports.World = world_1.default;
const object_set_1 = require("./collections/object-set");
exports.ObjectSet = object_set_1.default;
const watchable_object_set_1 = require("./collections/watchable-object-set");
exports.WatchableObjectSet = watchable_object_set_1.default;
const entity_removed_1 = require("./events/entity-removed");
exports.EntityRemoved = entity_removed_1.default;
const entity_event_processed_1 = require("./events/entity-event-processed");
exports.EntityEventProcessed = entity_event_processed_1.default;
const vector3_1 = require("./vector3");
Object.defineProperty(exports, "vector3", { enumerable: true, get: function () { return vector3_1.vector3; } });
