'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
exports.WatchableObjectSet = exports.ObjectSet = exports.World = exports.Trait = exports.Entity = void 0;
var entity_1 = require("./entity");
Object.defineProperty(exports, "Entity", { enumerable: true, get: function () { return entity_1.default; } });
const trait_1 = require("./trait");
exports.Trait = trait_1.default;
const world_1 = require("./world");
exports.World = world_1.default;
const object_set_1 = require("./collections/object-set");
exports.ObjectSet = object_set_1.default;
const watchable_object_set_1 = require("./collections/watchable-object-set");
exports.WatchableObjectSet = watchable_object_set_1.default;
